### PR TITLE
Remove redundant throws clause in CloudBlob#getName().

### PR DESCRIPTION
**Pull request by m-moris**
CloudBlob#getName() method has redundant throws clause and remove it.

### CODE REVIEW

**Comment by emgerner-msft** [comment]
Looks great, thanks! Have you signed the [CLA](http://azure.github.io/guidelines.html)?

**Comment by m-moris** [comment]
I have just signed the CLA.

**Comment by emgerner-msft** [comment]
Thanks! Could you please redirect this pull request to dev rather than master? We try to keep master equivalent to what we have released on Maven. Your fix will then go out in our next release from dev. Once that's done, we should be good to merge.

**Comment by m-moris** [comment]
I pull requested dev branch and close this.

**Pull request closed without merging**
